### PR TITLE
update getLoc()

### PR DESCRIPTION
**Pull request by ggarcz1**

### CODE REVIEW

**Comment by DanRowe** [comment]
Got a null pointer at Map.move

image

Can you change the destination for all these PR's to `p1-fixes`

**Comment by ggarcz1** [comment]
doesnt map.move need to be updated too?

**Comment by DanRowe** [comment]
Yeah we're waiting on @jmablanco for that

**Comment by DanRowe** [comment]
So temporarily merging into p1-fixes while things are broken. Then once it's all working we can go into main.

**Comment by ggarcz1** [comment]
ah ok bet it was giving me an error "There are no new commits between base branch 'p1-fixes' and head branch 'update-getLoc-map-class'"  but that's bc you already did the merge

**Comment by DanRowe** [comment]
Oh so I guess we can just close these then

**Comment by DanRowe** [comment]
Should work now

**Comment by DanRowe** [comment]
So ghosts still don't appear in the center box as mentioned by sagar in #64 but after some testing I think that's because of `map.move.`

**Review by DanRowe — APPROVED** [review]
Looks good! We will need to test again once `map.move` is finished.

**Pull request merged**
